version: '3.8'

services:
  db:
    image: mongo:5
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
